site_name: Distributed Charge

nav:
- Home: README.md

theme: material

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
  - codehilite
  - mkautodoc

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
